Update JS minor dependencies
at this point, does not build anymore due to:

TypeError: this._source.clearCache is not a function
    at CachedSource.clearCache (formol/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:478:17)